### ISSUE TITLE
Potential race condition between verification and copying files

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Coherence#1]
Since we're verifying a symlinked directory (project\dev\Latest\build), it's possible that path will be updated between verifying that package and copying it after verification passes.

We should probably resolve the symlink when we pick it as a candidate to avoid this.

**Comment by davidfowl** [comment]
@troydai was this fixed?

**Comment by troydai** [comment]
I don't think when I typed "#1" it means this issue. So it is not fixed. However, I never saw this happen ever since I begin working on Coherence.

**Comment by muratg** [comment]
@victorhurdugaci did you see this while working on the new CI?

**Comment by muratg** [comment]
Closing since it seems we don't hit this in practice.
