### ISSUE TITLE
Add sanity check for Microsoft.NETCore.UniversalWindowsPlatform

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Coherence#102]
In the past, we have had package restore issues with UWP. This has been primarily do to UWP lagging on supporting the latest contract versions on BCL packages. We should add a sanity check that it is possible to restore EF with UWP.

```json
{
    "dependencies": {
         "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0-*",
         "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-*",
         "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0-*", 
         "Microsoft.EntityFrameworkCore.Tools": {
              "type": "build",
              "version": "1.0.0-*"
         }
    },
    "frameworks": {
         "uap10.0": { }
     },
     "runtimes": {
           "win10-x86": { },
           "win10-x86-aot": { },
           "win10-x64": { },
           "win10-x64-aot": { },
           "win10-arm": { },
           "win10-arm-aot": { }
      }
}
```

**Comment by muratg** [comment]
@natemcmaster We can bring this back if it's blocking anything in RTM.

**Comment by natemcmaster** [comment]
Related note: even if we don't automate for RTM, this should be a sign off requirement.

**Comment by muratg** [comment]
https://github.com/aspnet/Release/issues/12

**Comment by Eilon** [comment]
@natemcmaster @divega @rowanmiller do we still need this? Still useful? Any plans to do it?

**Comment by natemcmaster** [comment]
Probably not useful at this point. BCL team has improved their processes.

**Comment by rowanmiller** [comment]
Yeah I think this has been much less of an issue. I'd like to get an ok from @bricelam before closing though.

**Comment by Eilon** [comment]
Okie dokie, thanks!

**Comment by bricelam** [comment]
Don't need this, but it would be nice if we mirrored the UWP dependency packages of NETStandard.Library on aspnetcore-dev so you don't have to also the dotnet-core feed

**Comment by Eilon** [comment]
@pranavkm can we mirror the package @bricelam mentions?

**Comment by pranavkm** [comment]
https://github.com/aspnet/CoreCLR/issues/142

**Comment by Eilon** [comment]
Ok cool, closing this issue then.
