### ISSUE TITLE
Remove package-dependencies from makefile.shade

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#110]
We no longer need to run DependenciesPackager as part of Coherence. cc @javiercn

**Comment by javiercn** [comment]
Yep, we can remove it from here, but we might keep a command to run a restore on ship\project.json to ensure the consistency of our shipping packages, this is incredibly useful in detecting misconfigured packages within our graph and missing third party dependencies we aren't accounting for.

**Comment by pranavkm** [comment]
@javiercn Coherence-Final still runs this. So we do have coverage, just later in the pipeline.
