### ISSUE TITLE
Remove references to Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#134]
Microsoft.DotNet.InternalAbstractions was refactored and renamed as part of 1.1 to Microsoft.DotNet.PlatformAbstractions. We should update our code to no longer reference this package:

https://github.com/search?q=org%3Aaspnet+InternalAbstractions&type=Code

**Comment by Eilon** [comment]
TODO: Split this bug into one bug for each affected repo.

**Comment by Eilon** [comment]
Farmed out to here:

* https://github.com/aspnet/Performance/issues/217
* https://github.com/aspnet/Scaffolding/issues/445
* https://github.com/aspnet/Docs/issues/3198
