### ISSUE TITLE
Re-enable Coherence verification

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#137]
Temporarily disabling this check since referencing older build of `Microsoft.Extension.DependencyModel` is causing the build to fail. This is a task to re-enable it once we pick up the new builds (possibly by EOD).

**Comment by dougbu** [comment]
As discussed offline, we should not have done this in the first place. Means Coherence will succeed with incoherent packages. More generally, should reserve disabling the dependency check for extreme situations since this is what Coherence is _about_.
