### ISSUE TITLE
Update TFMs of our samples and test apps from netcoreapp1.0 to netcoreapp1.1

### ISSUE THREAD

**Issue by halter73** [aspnet/Coherence#138]
@DamianEdwards explains "Just because the outer-most package _Microsoft.NETCore.App_ still only lists netcoreapp1.0 (which I agree is confusing) doesn’t mean there aren’t packages further down in the graph that target netcoreapp1.1 specifically. You’ll need to target netcoreapp1.1 in applications to ensure you get the right closure all the way down."

**Comment by pranavkm** [comment]
Would templates also need to be updated? cc @phenning

**Comment by pranavkm** [comment]
We figured this doesn't work for tools - dotnet \ NuGet assumes tools at most target `netcoreapp1.0`. The plan is to update samples and test applications for this release to target `netcoreapp1.1`.
