### ISSUE TITLE
Downgrade tools to target Microsoft.NETCore.App 1.0.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#141]
Following up the discussion to change the TFM for Microsoft.NETCore.App 1.1 to `netcoreapp1.1`, we should downgrade all our tools to target `Microsoft.NETCore.App 1.0.0`.

**Comment by Eilon** [comment]
@pranavkm @natemcmaster this is all done already, right?

**Comment by pranavkm** [comment]
Yup. @natemcmaster can confirm, but this can be closed.

**Comment by natemcmaster** [comment]
The MSBuild version of tools are targeting `Microsoft.NETCore.App 1.0.1`. Based on the outcome of our "prefercliruntime" feature of CLI, we may need to do work here.

**Comment by Eilon** [comment]
@natemcmaster ok, I'll park on your plate in the meantime.

**Comment by prafullbhosale** [comment]
I am assuming scaffolding needs to do this as well.

**Comment by natemcmaster** [comment]
Resolved by
https://github.com/aspnet/EntityFramework.Tools/pull/32
https://github.com/aspnet/Scaffolding/pull/358
https://github.com/aspnet/DotNetTools/pull/241
