### ISSUE TITLE
Add some automation to bump up patch versions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#147]
When a repository produces a patch build, we have to produce a patch for all the packages that consume it that reference the patched build. It would be useful to have some form of automation to support this.

See discussion at https://github.com/aspnet/Coherence-Patch/pull/21#issuecomment-257021134

**Comment by pranavkm** [comment]
@JunTaoLuo seemed super enthusiastic to do this 👍

**Comment by JunTaoLuo** [comment]
Holding off on more work on this issue since it's not clear if this is still needed after the migration to MSBuild.
