### ISSUE TITLE
Consider a configuration that builds Universe (compile + test) on xplat

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#149]
In our regular workflow, we create packages on Windows that are consumed in xplat tests. The partner mirroring wasn't setup this way - it attempts to build and test in parallel on all xplat scenarios. This often ends up finding issues in build (such as casing package Id incorrectness) which don't affect the package creation on Windows. Fixing it at the point that we're tying to pick up partner packages is problematic since it delays us from doing the actual task of verifying the correctness of partner packages.

**Comment by Eilon** [comment]
Closing because the value doesn't seem to be that much, compared to doing the work we have to do anyway when such a failure occurs.
