### ISSUE TITLE
Switch from SignalR-Server -> SignalR

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#151]
Modify UniverseCoherence \ Coherence to start building github.com/aspnet/SignalR instead of the current set of SignalR-* repos.

**Comment by pranavkm** [comment]
cc @davidfowl \ @anurse . Does this sound about right?

**Comment by davidfowl** [comment]
:shipit:, we should pin the last build of the older package on myget as well @Eilon

**Comment by Eilon** [comment]
Can certainly do that, but why? Was it any good?

**Comment by muratg** [comment]
@Eilon there (possibly) may be folks who restore that package.

**Comment by Eilon** [comment]
Per discussion, this is unlikely to be needed because until the new stuff builds, the old packages will be around.

**Comment by Eilon** [comment]
@pranavkm any further work here? Good to close?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Universe/commit/de71fc340b9238fe5f55010236c8705593eaaab4
