### ISSUE TITLE
Move SignalR-Client-CPP to https://github.com/aspnet/MicroBuild-Signed

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#152]
We don't build the package as part of Universe. We can independently sign it in the secondary signing service

**Comment by Eilon** [comment]
Where does the C++ client get signed today?

cc @moozzyk

**Comment by moozzyk** [comment]
I just added it to MicroSigned build yesterday - https://github.com/aspnet/MicroBuild-Signed/commit/cae3fca7326c2a9ec6fd514ee3c1ea824c63d229 so that we have signed bits to release.

I guess this issue can be closed now.

**Comment by Eilon** [comment]
Okie dokie.
