### ISSUE TITLE
Figure out a way to deal with new CoreCLR packages

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Coherence#159]
After a new successful build of CoreCLR, our Coherence check fails with errors like `Microsoft.Extensions.DependencyInjection.1.2.0-preview1-22941 depends on NETStandard.Library v[1.6.1, ) (.NETStandard,Version=v1.1) when the latest build is v1.6.2-beta-24816-02`.
I've temporarily disabled product packages verification.

cc' @Eilon @pranavkm

**Comment by Eilon** [comment]
Parking this on your plate until we can sync with @pranavkm .

**Comment by pranavkm** [comment]
Should be fixed now. I checked in changes to all the repos to start referencing the new CoreFx packages and turned the coherence check back on. We can close this once we have a Coherence build.

**Comment by Eilon** [comment]
How can we make this be more automatic?

**Comment by muratg** [comment]
@pranavkm Good to close?

**Comment by Eilon** [comment]
Doesn't appear to be any work left here. If this becomes a problem in the future we'll investigate.
