### ISSUE TITLE
Revert https://github.com/aspnet/Coherence/commit/133c9a945b6da13ba64f82ae2380434f145d1bea once we pick up new IdentityModel packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#163]
https://github.com/aspnet/Security/commit/fddfad14c9ce757717e4dfd2db5bf4f045b9d52e picked up packages from NuGet.org newer than the ones in the feed. This is causing Coherence to fail. However the 2.1.3-* packages on their nightly feeds are broken. Once we pick up the newer packages we need to update Security and remove this exclusion.

**Comment by pranavkm** [comment]
Assigned to @Tratcher to revert this change when Security is updated.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/commit/c18a3d3a7d9e9771638b74ad5c7777f33e4363a6

**Comment by pranavkm** [comment]
Btw, they have 2.1.4-* on their feeds now. I'm not entirely sure what our policy on their packages needs to be - should we pin to an earlier version that works?

**Comment by Tratcher** [comment]
Let's wait on 2.1.4, they're doing it for katana.
