### ISSUE TITLE
Use nuget.exe install \ nuget.exe push to create package directory

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#170]
We were using NuGet APIs to produce case-consistent expanded package directory and APIs to speed up pushing partner packages. Since the number of partner packages we push is significantly smaller now, we should switch to using the exe to do these operations rather than the API (which is very fast changing).

**Comment by natemcmaster** [comment]
What about xplat? "dotnet nuget push" exists, but AFAIK "dotnet nuget install" isn't available yet.

**Comment by pranavkm** [comment]
We don't run Coherence on xplat (as yet). So we can live without it. Plus the code can be revived if we ever decide to run it xplat.

**Comment by pranavkm** [comment]
Closing this - we actually need the retry + some cleverness around not passing keys to the `exec` task. Would be useful to turn this what we have here to a custom tool that we use in our builds.
