### ISSUE TITLE
Remove unnecessary package references

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#175]
We should do a scan and figure out if there are any package references we don't actually need in our projects. For instance, https://github.com/aspnet/Logging/pull/585

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by Eilon** [comment]
In theory the work is this:

1. Find all csproj files in all src folders in all repos
2. Delete all "System.*" package references
3. If it compiles, send a PR and get it merged
4. If it doesn't compile, figure out what's needed and go to step (3)

**Comment by pakrym** [comment]
I was thinking about checking which package dll's got optimized out from assembly references by compiler.

**Comment by Eilon** [comment]
@pakrym that could certainly work as well.
