### ISSUE TITLE
Remove old packages from the volatile feed automatically after a successful coherence build.

### ISSUE THREAD

**Issue by troydai** [aspnet/Coherence#22]

**Comment by troydai** [comment]
Working on this right now.

**Comment by muratg** [comment]
Was the MVC and Security failures do to this?

**Comment by Eilon** [comment]
The Security failure was unrelated - it was just a bad fix from me that @Tratcher fixed (thanks! :smile: )

The MVC failure was due to the missing CLR packages on the CI's local release volatile feed. And @pranavkm is fixing that. Not sure if it's exactly this issue.

**Comment by pranavkm** [comment]
It sort of is. It should get resolved once https://github.com/aspnet/CoreCLR/issues/40 is fixed (working on it next)
