### ISSUE TITLE
No need fail the build when a particular branch folder of a project is not found.

### ISSUE THREAD

**Issue by troydai** [aspnet/Coherence#23]
Check out this build log: http://projectk-tc/viewLog.html?buildId=141607&buildTypeId=Coherence&tab=buildLog. It fails because: 
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '\\projectk-tc\drops\docfx\release'.
```
This is not necessary since it simply means there is no release build for this project.

**Comment by muratg** [comment]
@troydai still an issue?

**Comment by troydai** [comment]
/cc @pranavkm 
since the old CI is not accessible and I didn't find any error recently related to this cause. I think we can close this.

**Comment by muratg** [comment]
:+1:
