### ISSUE TITLE
A lot of symbols/sources are missing from the share

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Coherence#29]
SanityCheck tries to push symbols and source for built packages to a share. To do that it uses the NuGet `pushsymbols` command (https://github.com/aspnet/Coherence/blob/dev/src/SanityCheck/Program.cs#L398). However half of the packages are missing from the share. Trying to manually reproduce this issue we found that is because sometimes the pushsymbols command fails with 'Package X already has a dependency defined for Package Y' which appears to be a bug in NuGet. Newer versions of NuGet no longer have the `pushsymbols` command - there is a `push` command but it works in a different way so the change is more involved.

**Comment by pranavkm** [comment]
* The CI uses a magical build of NuGet that had a  `pushsymbols` command. 
* We were running out of space and I ended up wiping out the symbols share once or twice in the past. 
* I think http://symbolsource.org fixed the issue with DNX packages. Perhaps we should try pushing there again?

**Comment by pranavkm** [comment]
Additionally with the new CI, using a file share is a non-starter.

**Comment by moozzyk** [comment]
@victorhurdugaci

**Comment by victorhurdugaci** [comment]
@pranavkm huh?

**Comment by muratg** [comment]
Bringing this back -- are we currently pushing symbols to symbolsource @pranavkm ?

**Comment by muratg** [comment]
:watch:

**Comment by pranavkm** [comment]
We are, although a bunch of them don't get published because we're using a super old build of nuget. I have no idea how we got that binary. Could we publish this to MyGet instead? I think they have a symbol server offering. cc @Eilon

**Comment by muratg** [comment]
I think pushing symbols to myget for dev/release branches are fine, though shouldn't we push to symbolsource for our nuget.org releases?

**Comment by Eilon** [comment]
If we push to MyGet we'll run out of space... we're already using ~10GB...

**Comment by muratg** [comment]
How about blob storage?  

But I think the more important question is, are we pushing all our symbols to symbolsource when we have releases? (i.e. when we push to nuget)

**Comment by Eilon** [comment]
Pushing stuff to blob storage isn't a solution - it's just another problem. Who manages that? Pays for it? Clears it out when it fills up? Makes it secure and with delegation?

I don't think we push any symbols anywhere at this time.

**Comment by Eilon** [comment]
Closing this because there's no specific action on this issue. We do now have symbols, we just don't have a policy on where to push them. That's being figured out with the .NET team.
