### ISSUE TITLE
Unused packages in coherence

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Coherence#39]
There are some packages that we pull in like `Microsoft.CodeAnalysis.Scripting.Common` which we do not need and can cause problems in our code. For example, packages without explicit target frameworks were causing exceptions in `CoherenceVerifier` which was temporarily resolved by #38. We need a long term solution based on some sort of black/white list of required packages.

cc @davidfowl @pranavkm

**Comment by pranavkm** [comment]
#38 looks like the right fix though - a package can't be non\in-coherent if it has no dependencies

**Comment by JunTaoLuo** [comment]
I guess the fix we had is sufficient then? Closing for now. @davidfowl, please reopen this if we should look into other solutions.
