### ISSUE TITLE
Set up a gated dependency pull for IdentityModel packages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Coherence#40]
The security repo depends on a few different IdentityModel packages. It currently resolves these from a myget feed. However, sometimes those packages depend on a later version of CoreCLR than us, so it fails trying to restore dependencies. They also sometimes make breaking changes.

Establish a gated CI build that pulls from their feed (nightly or release) compiles and tests Security (and MusicStore?), and pushes the verified packages to our own feed.

One related issue we have is that the IdentityModel packages maintain their build numbers when shipped to nuget.org (http://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/2.0.0-beta8-210131116). When our project.json references use -rc1-*, our final nuget.org release builds end up targeting -rc1 of their packages. We could work around this by automatically stamping the needed build number into the project json, or perhaps stamping it directly into the output packages.

**Comment by muratg** [comment]
@pranavkm @Eilon As we progress into RC2, this would be more important than the other gate mechanisms

**Comment by Eilon** [comment]
@Tratcher can you work with our CI experts to set this up?

**Comment by pranavkm** [comment]
In this case, do we want to test the package beside attempting to restore it with the version of CoreCLR packages we have?

**Comment by Tratcher** [comment]
cross-checking with coreclr is the most important.

**Comment by muratg** [comment]
@Tratcher Was this done?  What's the associated check-in?

**Comment by Tratcher** [comment]
Yes
https://github.com/aspnet/CoreCLR/commit/47f579e57c6e8efc8b9e5ad99843b5f3fa55ede3
https://github.com/aspnet/Security/commit/0db9a16c915ba5e686f6e001af82853edca63e09

**Comment by muratg** [comment]
Thanks!
