### ISSUE TITLE
Keep track of packages already pushed to the feed

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#5]
Today we end up pushing all packages to the feed as part of Coherence. CoreCLR packages consequently end up getting pushed multiple times through out the day.

We could make the push smarter by keeping track of what was last pushed and only pushing those that do not exist on the feed or are different.

**Comment by davidfowl** [comment]
@pranavkm Still need this?

**Comment by pranavkm** [comment]
Nope - this should either be fixed or we don't care
