### ISSUE TITLE
Fix error message for incoherent packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#69]
`Expected Microsoft.NETCore.App (ï¿½ 1.0.0-rc2-23931)(netstandard15) but got 1.0.0-rc2-24008`

It should say 'the package was compiled against Microsoft.NETCore.App (1.0.0-rc2-23931) but the most recent version is 1.0.0-rc2-24008` or something like that.

**Comment by muratg** [comment]
:+1:

**Comment by pranavkm** [comment]
This was fixed in https://github.com/aspnet/Coherence/commit/db4edc1410c8ef5ff72e6cd814e185cd00e4c0f0
