### ISSUE TITLE
Libuv packages are marked as non-shipping

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#70]
* Microsoft.AspNetCore.Internal.libuv-Darwin and Microsoft.AspNetCore.Internal.libuv-Windows are marked as non-shipping while the Linux one is marked as shipping. Consequently these packages don't get published to cidev \ vnext by Coherence and Coherence-Signed.

**Comment by pranavkm** [comment]
cc @halter73 \ @phenning

**Comment by pranavkm** [comment]
cc @muratg - was this intentional? If not, we need to fix this for rc2

**Comment by muratg** [comment]
@pranavkm No this wasn't intentional. Please mark them as shipping.
