### ISSUE TITLE
Pick up .build directory from UniverseCoherence

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#73]
Need to follow up on https://github.com/aspnet/Universe/commit/6667fd0748cbb684006ad4d430c70983de5d7263 and pick up the .build directory we drop during UniverseCoherence.

**Comment by pranavkm** [comment]
cc @Eilon - could you have some one look into this? We didn't pipe the .build directory all the way from UniverseCoherence -> Coherence.

**Comment by Eilon** [comment]
@victorhurdugaci can you take a crack at this?

**Comment by victorhurdugaci** [comment]
Sure, I can take a look
