### ISSUE TITLE
Microsoft.Extensions.DependencyModel is listed as ship instead of ext

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#94]
This is a 3rd party package that is marked as `ship`. Consequently we modify it to be a timestamp free version in coherence and modify packages that depend on it to be timestamp free. This produces a downgrade warning:

```
warn : Detected package downgrade: Microsoft.Extensions.DependencyModel from 1.0.0-rc2-final to 1.0.0-rc2-002702 
warn :  Packages-NoTimeStamp (>= 1.0.0) -> Microsoft.AspNetCore.Mvc.Core (>= 1.0.0-rc2-final) -> Microsoft.Extensions.DependencyModel (>= 1.0.0-rc2-final) 
warn :  Packages-NoTimeStamp (>= 1.0.0) -> Microsoft.Extensions.DependencyModel (>= 1.0.0-rc2-002702)
```

**Comment by pranavkm** [comment]
cc @Eilon \ @muratg \ @victorhurdugaci

**Comment by Eilon** [comment]
We'll fix in RTM.

**Comment by Eilon** [comment]
@pranavkm is this covered by https://github.com/aspnet/Coherence/pull/96?

**Comment by pranavkm** [comment]
Yup

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Coherence/commit/db4edc1410c8ef5ff72e6cd814e185cd00e4c0f0
