### ISSUE TITLE
Fix sanity check failures

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#97]
* [x] Microsoft.AspNetCore.Authentication.1.0.0-rc3-20932 depends on System.Net.Http v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Cryptography.KeyDerivation.1.0.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Http.Abstractions.1.0.0-rc3-20932 depends on System.Linq.Expressions v[4.0.11-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Identity.1.0.0-rc3-20932 depends on System.Text.RegularExpressions v[4.0.12-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Identity.EntityFrameworkCore.1.0.0-rc3-20932 depends on System.ComponentModel.TypeConverter v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.JsonPatch.1.0.0-rc3-20932 depends on System.ComponentModel.TypeConverter v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Mvc.Abstractions.1.0.0-rc3-20932 depends on System.ComponentModel.TypeConverter v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Mvc.Razor.Host.1.0.0-rc3-20932 depends on System.ComponentModel.TypeConverter v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Mvc.WebApiCompatShim.1.0.0-rc3-20932 depends on System.Net.Http v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Proxy.0.1.0-rc3-20932 depends on System.Net.Http v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Razor.1.0.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Razor.Runtime.1.0.0-rc3-20932 depends on System.Text.RegularExpressions v[4.0.12-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Routing.1.0.0-rc3-20932 depends on System.Text.RegularExpressions v[4.0.12-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Server.Testing.1.0.0-rc3-20932 depends on System.Net.Http v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Server.Testing.1.0.0-rc3-20932 depends on System.Text.RegularExpressions v[4.0.12-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.Session.1.0.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.SignalR.Messaging.0.1.0-rc3-20932 depends on System.Linq.Expressions v[4.0.11-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.SignalR.Messaging.0.1.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.TestHost.1.0.0-rc3-20932 depends on System.Net.Http v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.AspNetCore.WebSockets.Protocol.0.1.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.EntityFrameworkCore.Relational.1.0.0-rc3-20932 depends on System.Text.RegularExpressions v[4.0.12-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.Extensions.Configuration.Binder.1.0.0-rc3-20932 depends on System.ComponentModel.TypeConverter v[4.0.1-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc3-20932 depends on System.Linq.Expressions v[4.0.11-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.Extensions.Options.1.0.0-rc3-20932 depends on System.Linq.Expressions v[4.0.11-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.Net.WebSockets.Server.0.1.0-rc3-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.
* [x] Microsoft.VisualStudio.Web.CodeGeneration.1.0.0-preview2-20932 depends on System.Linq.Expressions v[4.0.11-rc2-24027, ) when the latest build is v4.1.0-rc3-24116-00.
* [x] Microsoft.VisualStudio.Web.CodeGeneration.Utils.1.0.0-preview2-20932 depends on System.Security.Cryptography.Algorithms v[4.1.0-rc2-24027, ) when the latest build is v4.2.0-rc3-24116-00.

**Comment by pranavkm** [comment]
cc @NTaylorMullen \ @ryanbrandenburg \ @ajaybhargavb \ @BrennanConroy

**Comment by pranavkm** [comment]
cc @JunTaoLuo

**Comment by pranavkm** [comment]
The minor \ build versions for CoreFx packages have changed in rc3. Could you update the project.jsons so that it will pick up the rc3 versions. For instance https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/project.json#L29 would change to ` "System.Linq.Expressions": "4.1.0-*",` per the error

**Comment by Eilon** [comment]
@JunTaoLuo looks like you're working on this, so assigning to you.

**Comment by pranavkm** [comment]
We were sort of sharing the burden here :smile:

**Comment by Eilon** [comment]
I'll assign to Johnav Lushnamoorthy.

**Comment by pranavkm** [comment]
Thanks @JunTaoLuo !

**Comment by pranavkm** [comment]
The current plan is to revert these changes and go back to rc2 CoreFx \ CLI. I'll leave these open when we need to redo these again.

**Comment by JunTaoLuo** [comment]
@pranavkm any idea when this needs to be done again?

**Comment by pranavkm** [comment]
Not until we switch back to the RC3 packages. This is waiting on https://github.com/dotnet/cli/pull/3138

**Comment by JunTaoLuo** [comment]
Updated all the repos

**Comment by pranavkm** [comment]
:clap:

**Comment by pranavkm** [comment]
A couple more that seem to be new:

* [ ]  Microsoft.EntityFrameworkCore.Relational.1.0.0-rc3-21101 depends on System.Data.Common v[4.0.1-rc2-24027, ) (.NETStandard,Version=v1.3) when the latest build is v4.1.0-rc3-24127-00.
* [ ]  Microsoft.EntityFrameworkCore.1.0.0-rc3-21101 depends on System.Collections.Immutable v[1.1.37, ) (.NETFramework,Version=v4.5.1) when the latest build is v1.2.0-rc3-24127-00.
* [ ]  Microsoft.EntityFrameworkCore.1.0.0-rc3-21101 depends on System.Collections.Immutable v[1.1.37, ) (.NETStandard,Version=v1.3) when the latest build is v1.2.0-rc3-24127-00.
* [ ]  Microsoft.Data.Sqlite.1.0.0-rc3-21101 depends on System.Data.Common v[4.0.1-rc2-24027, ) (.NETStandard,Version=v1.3) when the latest build is v4.1.0-rc3-24127-00.

@AndriySvyryd \ @natemcmaster is it ok if we switch to using the the CoreFx produced builds of `System.Collections.Immutable`?

**Comment by natemcmaster** [comment]
Are these new API versions supported on UWP?

**Comment by pranavkm** [comment]
@natemcmaster here's the package info - https://github.com/aspnet/Coherence/commit/db4edc1410c8ef5ff72e6cd814e185cd00e4c0f0

**Comment by JunTaoLuo** [comment]
Updated a few more reference. will keep this open to see if there are any others that I have missed.

**Comment by JunTaoLuo** [comment]
I don't see any more issues related to this in our Coherence build. Closing.
